### PR TITLE
Implemented basic stuff

### LINKED ISSUE #4: Setup basic django framework
Involves setting up a Django framework with appropriate make files and documentation on using the same.

### PR DESCRIPTION
**Pull request by pscyk**
built basic backend

### CODE REVIEW

**Comment by fireballpoint1** [comment]
@95ych you will need to update the PR to the develop branch and inside the `src/` directory

**Comment by pscyk** [comment]
should i keep the bin/ and lib/ (virtual env stuff) outside the src/ or keep everything related inside src/
@fireballpoint1

**Comment by fireballpoint1** [comment]
@95ych everything for django should be inside src folder

**Comment by fireballpoint1** [comment]
Also, you need to pull develop and resolve all conflicts.

**Comment by fireballpoint1** [comment]
@95ych i don't see the virtual env files or a make file here

**Comment by 95ych** [comment]
added missing parts

**Comment by pscyk** [comment]
@fireballpoint1 
Missing parts added

**Comment by fireballpoint1** [comment]
@95ych Your instructions to run the django server are imcomplete. Please write them in a way that even a first time user of django can run the project .

**Review by fireballpoint1 — APPROVED** [review]

**Comment by fireballpoint1** [comment]
@95ych Approved. resolve conflicts and rebase and merge

**Pull request merged**
